language: node_js

node_js:
  - '8'
  
go: '1.10'

before_install:
  - sudo apt-get install -y tree

install:
  - tree -L 3 ~/.ghq
  - go get github.com/motemen/ghq
  - npm install
  
script:
  - node index.js
  - tree -L 3 ~/.ghq
